# opted to use environment.php for performance reasons

config:
  web_root: /Users/amdayton/Sites/mnkino.com/
  mail_to: mnkino@gmail.com
  flickr_api_key: ''
  admin_username: ''
  admin_password: ''
  blip_tv_username: ''
  blip_tv_password: ''
  blip_tv_url: ''
  flickr_username: ''
  flickr_password: ''
  flickr_url: '' 
  
databases:
  dev:
    server: 'localhost'
  	username: 'root'
  	password: 'falilv33'
  	database: ''
  